[workspace]

members = [
  "tokio",
  "examples",
  "tokio-util",
]
exclude = [
  "tokio-macros",
  "tokio-test",
  "tokio-stream",

    # Internal
  "benches",
  "stress-test",
  "tests-build",
  "tests-integration",
]
